# THIS YAML FILE EXECUTE A SHELL SCRIPT IN TWO SLAVE MACHINE


 Step1-create a file add_text.sh in Ansible master machine and write script.
       #sudo nano add_text.sh
       
       #!/bin/bash
       echo "the txt has been added by custom script" >> /tmp/1.txt
       
Step2- create a playbook and add group name production for run this particular script.

       # sudo nano run_script.yml
       # ansible-playbook run_script.yml --syntax-check
       # ansible-playbook run_script.yml


      After that automatically created file in slave machine 


---
- name: Run custom script and add Ubuntu user
  hosts: production
  become: yes  # To execute tasks with root privileges

  tasks:
    - name: Transfer script to target hosts
      copy:
        src: add_text.sh
        dest: /tmp/add_text.sh
        mode: '0755'
      become: yes

    - name: Run custom script
      shell: /tmp/add_text.sh
      become: yes

