---
- name: Install Java
  hosts: slave1
  become: yes  # To execute tasks with root privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk  # You can change the version as needed
        state: present
      become: yes



- name: Install MySQL Server
  hosts: slave2
  become: yes  # To execute tasks with root privileges

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      become: yes
